<?php include 'header.phtml';?>

		<div class="sixteen columns">
			<a href="/lists" class="full-width button">View all lists</a>
		</div>

		<div class="sixteen columns">
			<div class="add-list">
				<input type="text" class="ten columns" id="listTitle" placeholder="Add a list title">
			</div>
			<div class="list-components hidden">
				<h2 class="list_title"></h2>
				<input type="hidden" name="list_id" id="list_id">
				<div class="clearfix">
					<input type="text" class="ten columns" id="list_item" placeholder="Add something here"/>
				</div>
				<div class="components"></div>
				<button id="done" class="full-width">Done Editing!</button>
			</div>			
		</div>

<?php include 'footer.phtml';?>